### ISSUE TITLE
项目中的baseUrl应该写什么？

### ISSUE THREAD

**Issue by zhuyuanwen** [wuyawei/fe-code#1]
写了`let baseUrl = 'http://localhost:63342/webrtc-stream/webrtc-main';` 提示error` Invalid options in vue.config.js: "publicPath" is not allowed`，写本地文件目录也不对。请问应该写什么？

**Comment by wuyawei** [comment]
config 里的 baseUrl 改成 publicPath ，这是vue-cli3.0更新后调整的
